### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/shadyyx/atom:'

### ISSUE THREAD

**Issue by shadyyx** [joefitzgerald/go-config#22] opened 2016-03-18 12:20 UTC
Hi there!

I am using Atom editor for GoLang and I am pretty happy with it. Yesterday and today I got a notice to upgrade some packages, so I did, between others it was go-plus and go-config (and some others go packages probably as well). Nevertheless, by my mistake my laptop got restarted just a while ago and to my surprise after starting it again and running Atom I've found out that GO support for Atom is not working anymore... It wanted me to upgrade the editor to latest version what I did.

When I start Atom it immediately says it would like to download gocode tool, by running `go get -u github.com/nsf/gocode`. I can immediately click on `Run go get` which gives me this error:

> package github.com/nsf/gocode: cannot download, $GOPATH not set. For more details see: go help gopath

which is not true because the gocode tool is already installed on my PC and if I run the same command from cli it successfully does something (no error, no new install as I already have it installed).
Running `$GOPATH` in my cli also returns the correct path...

The settings in _go-plus_ package also has the correct paths (both to GOPATH and Go install).

Now if I am editing a `.go` file and I trigger save, I immediately get an error

> Uncaught Error: ENOENT: no such file or directory, lstat '/home/shadyyx/atom:'

which I thought is just some typo so I wanted to _fix_ it by creating symlink `atom:` to `.atom/` in my HOME dir. But after that I get another error

> Uncaught Error: ENOENT: no such file or directory, lstat '/home/shadyyx/.atom/config'

so I guess there's something wrong completely. I don't know where, though.

Is it `go-plus` or `go-config` package? I would appreciate really quick response... :-)

Regards
shadyyx

**Comment by c2h5oh** [comment] 2016-03-18 15:17
Same problem in Atom 1.5. After upgrade to 1.6 works fine.

**Comment by virtuallynathan** [comment] 2016-03-18 15:33
Same issue here, still doesn't work in 1.6 even after a full reinstall.

**Comment by shadyyx** [comment] 2016-03-18 16:26
The problem is probably in the **gofmt** package. I realized that after changing the *Formatting tool* in Settings of **gofmt** package from `gofmt` to any other option (either `goimports` or `goreturns`) there's no more error at save... Still not sure whether it relates to **go-config** or not...

**Comment by amitdesai555** [comment] 2016-03-18 21:55
Same error with 1.6... is there a way we can revert our updates?

**Comment by joefitzgerald** [comment] 2016-03-18 22:41
Sorry you're having issues. If you are on OS X, please either:

1. Install Atom Beta (https://atom.io/beta) so you are running >= v1.7.0 of Atom
1. **Always** launch `atom` from the terminal (after quitting all instances of it launched by `Dock`, `Finder`, `Spotlight`; to be safe, just quit all instances of Atom)

The issue is related to a quirk in the way Atom was handling the environment. I fixed this with @lee-dohm in https://github.com/atom/atom/pull/11054, but this is only included in the 1.7.x releases and later.

If you're on Linux (specifically Ubuntu et al.) there may be another issue in play here.

**Comment by shadyyx** [comment] 2016-03-18 22:50
Unfortunately, I'm on Ubuntu 15.10. But I'll try the 1.7.0 Beta on Monday if this issue is not resolved by that time (which I will be more than happy as I don't want to use betas at work).

**Comment by amitdesai555** [comment] 2016-03-18 23:07
for windows users?

**Comment by shadyyx** [comment] 2016-03-20 16:36
OK, so I tried the 1.7.0 beta. I installed updates for few packages and the result is:
- no *exceptions* on save with `gofmt`; `goreturns` and `goimports` do not work - the same as before
- nevertheless, `gofmt` does not work as well - creating syntax errors in code does not raise any "Syntax errors" reported on file save...
- making changes in settings of `gofmt` package asks again to run `go get -u ...` and after clicking on provided button I get the same error as before

> **Error getting package** package sourcegraph.com/sqs/goreturns: cannot download, $GOPATH not set. For more details see: go help gopath

**Big finding**
After reading the documentation for `go-config` package where dependency to `environment` package is mentioned and reading the documentation for `environment` package I have realized that I am running the Atom IDE from a launcher icon. After running `atom-beta` from cli everything is working fine...

**Summary:** Is it possible to fix these issues  for the case when Atom IDE is run from a launcher?

**Comment by joefitzgerald** [comment] 2016-03-24 22:56
> [...] so I wanted to fix it by creating symlink atom: to .atom/ in my HOME dir [...]

You shouldn't create any symlinks.

Please update to the latest version of `environment` (and all other packages for that matter).

What is the contents of your PATH? Could you type `⌘-option-i`, go to the "console" tab, type `process.env.PATH`, and copy the resulting text into the issue?

**Comment by joefitzgerald** [comment] 2016-03-29 18:32
https://github.com/joefitzgerald/go-config/issues/23#issuecomment-203040293

**Comment by joefitzgerald** [comment] 2016-03-29 23:02
Closing this in deference to #23, where we have identified the root cause.

**Closed by joefitzgerald** 2016-03-29 23:02 UTC
